language: python
sudo: false

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libc6
      - g++
      - gfortran
      - libgsl0ldbl
      - zip

python:
  - 2.7
  - 3.5

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -q conda-build
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION setuptools cython numpy scipy numba
  - conda install -q -n test-environment -c r rpy2
  - source activate test-environment

install: python setup.py install

before_script:
    - pwd
    - ls
    - pushd $HOME
    - pwd
    - ls
    - wget http://pngu.mgh.harvard.edu/~purcell/plink/dist/plink-1.07-x86_64.zip
    - ls
    - unzip plink-1.07-x86_64.zip
    - ls
    - export PATH="$HOME/plink-1.07-x86_64:$PATH"
    - ls
    - hash -r
    - popd
    - ls $HOME/plink-1.07-x86_64
    - which plink

script: python setup.py test
