language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis/install_pandoc.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import sys; import limix_ext; sys.exit(limix_ext.test())"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  on:
    distributions: sdist bdist_wheel
    repo: Horta/limix-ext
