language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.5
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- conda install rpy2 -c r -y -q
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- conda install rpy2 -c r -y -q
- pwd
- find .
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- conda install rpy2 -c r -y -q
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import limix_ext; limix_ext.test()"
- popd
notifications:
  email: false
branches:
  only:
  - master
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: t9g1+6zSEXTFbTqrs7Y4EX49NTvgwdrlhcjOe52H8+N12YXXRDZJYilpxO29yCxjHGco/2Gnjm+4OkPu+RVw9c0ZqYxlevKsghC1JiA+A51JzJIVACY1UlPUqYguG+IzbR/4moA8jM6eHnuEnTDCmrjj4gkQgWvXRnNqk8YDnBiVneId3BYyOAVK3UR0bxK+3OaXIPOJJ3gbALUk1dcX36Lbkjaqfq4ffiVrjrDgGRMa0S+r2+jkpEFyiSVeEBoH1DkD3MDivGvcWnm1xCLlb5QzZxdVaynZ2cbg+bbxFlW6skLcaJ7G6x8yj1gDBfofuagqIgHD2v2Ka64Bcju5dEWqHbD3yq7ViBgEpbyrDlDRmpn06OErGcwswi1SQ1Bnj1B9lqRcn7vh9N+bzfsYPtCcGbxce+AhAk6DG5kHN9W19GgHikstuB79XRhxGYUvz9SQlzSTc0Aox7cHsJBqWJb/yzPwHjBKo63SYmrYat6KiUY1voDevoz4noRu2NjSin7bglNjqCBRHT86qKnnUf0ySOL+BY5+wdN01qcIS4x77GwMej7dlY2lWktz1QUJMaIRnL1wJJY/CI8pnDk9WEnzxtdI4OI9IZaVsPhf1ESL3u67/Csmn9mlajLJHq5HpgJbiKfKMQ8R4tHD51pFZCu8n6b2heR8o19l+LTSJlA=
  on:
    distributions: sdist bdist_wheel
    repo: Horta/limix-ext
